#Создание нового комментария

POST http://localhost:3000/api/comments/fb527bed-f30b-4fd7-8339-5d738693cab2 HTTP/1.1
Content-Type: application/json

{
  "userId":"67645530e791c623065e30c1",
  "text":"Comment text super super"
}
###

#Получение комментариев публикации

GET http://localhost:3000/api/comments/publication/8600dbb0-100d-4d48-b4e0-056cc840cd6e HTTP/1.1
Content-Type: application/json

###


#Удаление комментария по ID

DELETE http://localhost:30001/api/comments/fb527bed-f30b-4fd7-8339-5d738693cab2 HTTP/1.1
###
