#Создание нового комментария

POST http://localhost:3001/api/comments/8600dbb0-100d-4d48-b4e0-056cc840cd6e HTTP/1.1
Content-Type: application/json

{
  "userId":"658170cbb954e9f5b905ccf4",
  "text":"Comment text"
}

###

#Получение комментариев публикации

GET http://localhost:3001/api/comments/publication/8600dbb0-100d-4d48-b4e0-056cc840cd6e HTTP/1.1
Content-Type: application/json

###


#Удаление комментария по ID

DELETE http://localhost:3001/api/comments/1d375f85-bd75-4861-be57-2b9f4169fe98 HTTP/1.1
Content-Type: application/json

###
