version: '3.9'
services:
  mongo.userreadme:
    image: mongo:6
    restart: always
    env_file:
      - .env
    container_name: mongo.userreadme

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    healthcheck:
      test: ["CMD", 'db.runCommand("ping").ok', mongosh, localhost:27017/readme, --quiet]
      interval: 10s
      timeout: 10s
      retries: 5

    volumes:
      - mongo.userreadme:/data/db

  readme.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.ui
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo.userreadme:${MONGO_PORT}/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo.userreadme:
