version: '3.9'
services:
  mongo.userreadme:
    image: mongo:4.4
    restart: always
    container_name: mongo.userreadme

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - mongo.userreadme:/data/db

  readme.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.ui
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo.userreadme:${MONGO_PORT}/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo.userreadme:
